# .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags starting with v (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest # Use a Linux runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for changelog generation

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22' # Specify the Go version you are using

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest # Use the latest Goreleaser version
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_TOKEN }}
